## The bias of Cohen's $\bf d_s$ is twice as large as the bias of Shieh's $\bf d_s$ when population variances and sample sizes are equal across groups: mathematical demonstration. 

As mentioned in Table 1, the bias of Cohen's $d_s$ is defined as 
\begin{equation} 
Bias_{Cohen's \; d{_s}}= \delta_{Cohen} \times \left( \frac{\sqrt{\frac{df_{Student}}{2}} \times \Gamma{\left(\frac{df_{Student}-1}{2}\right)}}{\Gamma{\left( \frac{df_{Student}}{2}\right)}} -1 \right)
(\#eq:Cohenbias)
\end{equation} 
with 
\begin{equation*} 
\delta_{Cohen}=\frac{\mu_1-\mu_2}{\sqrt{\frac{(n_1-1)\times \sigma^2_1+(n_2-1)\times\sigma^2_2}{n_1+n_2-2}}}
(\#eq:Cohendelta)
\end{equation*} 
and 
\begin{equation*} 
df_{Student}=n_1+n_2-2
(\#eq:Cohendf)
\end{equation*}

As mentioned in Table 2, the bias of Shieh's $d_s$ is defined as 
\begin{equation} 
Bias_{Shieh's \; d{_s}}=\delta_{Shieh} \times \left( \frac{\sqrt{\frac{df_{Welch}}{2}} \times \Gamma{\left(\frac{df_{Welch}-1}{2}\right)}}{\Gamma{\left( \frac{df_{Welch}}{2}\right)}} -1 \right)
(\#eq:Shiehbias)
\end{equation} 
with 
\begin{equation*} 
\delta_{Shieh}=\frac{\mu_1-\mu_2}{\sqrt{\frac{\sigma^2_1}{n_1/N}+\frac{\sigma^2_2}{n_2/N}}} \quad (N=n_1+n_2)
(\#eq:Shiehdelta)
\end{equation*} 
and 
\begin{equation*} 
df_{Welch}=\frac{\left(\frac{\sigma^2_1}{n_1}+\frac{\sigma^2_2}{n_2} \right)^2}{\frac{(\sigma^2_1/n_1)^2}{n_1-1}+\frac{(\sigma^2_2/n_2)^2}{n_2-1}}
(\#eq:Welchdf)
\end{equation*}

When $n_1=n_2=n$ and $\sigma_1=\sigma_2=\sigma$, $\delta_{Cohen}$ is twice larger than $\delta_{Shieh}$, as shown below in equations \ref{eq:Cohendeltavarbalanced} and \ref{eq:Shiehdeltavarbalanced}:
\begin{equation} 
\delta_{Cohen}=\frac{\mu_1-\mu_2}{\sqrt{\frac{2(n-1)\sigma^2}{2(n-1)}}}=\bf \frac{\pmb \mu_1- \pmb \mu_2}{\pmb \sigma}
(\#eq:Cohendeltavarbalanced)
\end{equation} 
\begin{equation} 
\delta_{Shieh}=\frac{\mu_1-\mu_2}{\sqrt{2\left( \frac{\sigma^2}{n/(2n)}\right)}}=\bf \frac{\pmb \mu_1-\pmb\mu_2}{2\pmb\sigma}
(\#eq:Shiehdeltavarbalanced)
\end{equation}   
Moreover, degrees of freedom associated with Student's *t*-test and Welch's *t*-test are identical, as shown below in equations \ref{eq:Studentdfvarbalanced} and \ref{eq:Welchdfvarbalanced}:
\begin{equation} 
df_{Student}=\bf 2(n-1)
(\#eq:Studentdfvarbalanced)
\end{equation}
\begin{equation} 
df_{Welch}=\frac{\left[2(\sigma^2/n)\right]^2}{\frac{2(\sigma^2/n)^2}{n-1}}= \bf 2(n-1)
(\#eq:Welchdfvarbalanced)
\end{equation}

Equations \ref{eq:Cohenbias} and \ref{eq:Shiehbias} can therefore be redefined as follows:
\begin{equation} 
Bias_{Cohen's \; d{_s}}=\frac{\mu_1-\mu_2}{\sigma} \times \left( \frac{\sqrt{n-1} \times \Gamma{\left(\frac{2n-3}{2}\right)}}{\Gamma{\left( n-1\right)}} -1 \right)
(\#eq:Cohenbiasvarbalanced)
\end{equation} 
\begin{equation} 
Bias_{Shieh's \; d{_s}}=\frac{\mu_1-\mu_2}{\bf 2\sigma} \times \left( \frac{\sqrt{n-1} \times \Gamma{\left(\frac{2n-3}{2}\right)}}{\Gamma{\left( n-1\right)}} -1 \right)
(\#eq:Shiehbiasvarbalanced)
\end{equation} 

We can therefore conclude that the bias of Cohen's $d_s$ is twice larger than the bias of Shieh's $d_s$.

\newpage

## The variance of Cohen's $\bf d_s$ is four times larger than the bias of Shieh's $\bf d_s$ when population variances and sample sizes are equal across groups: mathematical demonstration.

The variance of Cohen's $d_s$ is defined in Table 1 as 
\begin{equation}
Var_{Cohen's \; d{_s}}=\frac{N\times df_{Student}}{n_1n_2 \times (df_{Student}-2)} + \delta^2_{Cohen} \left[ \frac{df_{Student}}{df_{Student}-2} - \left( \frac{\sqrt{\frac{df_{Student}}{2}} \times \Gamma{\left(\frac{df_{Student}-1}{2}\right)}}{\Gamma{\left( \frac{df_{Student}}{2}\right)}} \right)^2\right]
(\#eq:Cohenvar)
\end{equation} 
and the variance of Shieh's $d_s$ is defined in Table 2 as
\begin{equation}
Var_{Shieh's \; d{_s}}=\frac{df_{Welch}}{(df_{Welch}-2)N}  + \delta^2_{Shieh} \left[ \frac{df_{Welch}}{df_{Welch}-2} - \left( \frac{\sqrt{\frac{df_{Welch}}{2}} \times \Gamma{\left(\frac{df_{Welch}-1}{2}\right)}}{\Gamma{\left( \frac{df_{Welch}}{2}\right)}} \right)^2 \right]
(\#eq:Shiehvar)
\end{equation} 

We have previously shown in equations \ref{eq:Studentdfvarbalanced} and \ref{eq:Welchdfvarbalanced} that degrees of freedom associated with Student's *t*-test and Welch's *t*-test equal $2(n-1)$, when $n_1=n_2=n$ and $\sigma_1=\sigma_2=\sigma$. As a consequence, the first term of the addition in equation \ref{eq:Cohenvar} is 4 times larger than the first term of the addition in equation \ref{eq:Shiehvar}: 
$$\frac{N\times df_{Student}}{n_1n_2 \times (df_{Student}-2)}=\frac{2n\times 2(n-1)}{n^2 \times (2n-4)} =\bf \frac{4(n-1)}{n(2n-4)}$$
$$\frac{df_{Welch}}{(df_{Welch}-2)N} = \frac{2(n-1)}{2n(2n-4)}= \bf \frac{n-1}{n(2n-4)}$$
We have also previously shown in equations \ref{eq:Cohendeltavarbalanced} and \ref{eq:Shiehdeltavarbalanced} that $\delta_{Cohen}$ is twice larger than $\delta_{Shieh}$ when $n_1=n_2=n$ and $\sigma_1=\sigma_2=\sigma$ and, therefore, $\delta^2_{Cohen}$ is four times larger than $\delta^2_{Shieh}$. As a consequence, the second term of the addition in equation \ref{eq:Cohenvar} is also 4 times larger than the second term of the addition in equation \ref{eq:Shiehvar}. Because both terms of the addition in equation  \ref{eq:Cohenvar} are four times larger than those in equation \ref{eq:Shiehvar}, we can conclude that the variance of Cohen's $d_s$ is four times larger than the variance of Shieh's $d_s$.
